### ISSUE TITLE
根目录 npm start 报错

### ISSUE THREAD

**Issue by xxxsf** [aemoe/fairy#12]
MacBook-Pro:fairy jack$ npm start

> fairy@1.0.0 start /Users/alan/Desktop/fairy
> cd client && npm run build && cd ../  && cross-env NODE_ENV=production pm2 start ./app.js  --watch

> mo@1.0.0 build /Users/alan/Desktop/fairy/client
> npm run clean && npm run build:webpack

> mo@1.0.0 clean /Users/alan/Desktop/fairy/client
> rimraf ../public

sh: rimraf: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mo@1.0.0 clean: `rimraf ../public`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mo@1.0.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alan/.npm/_logs/2018-10-14T02_39_24_992Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mo@1.0.0 build: `npm run clean && npm run build:webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mo@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alan/.npm/_logs/2018-10-14T02_39_25_017Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fairy@1.0.0 start: `cd client && npm run build && cd ../  && cross-env NODE_ENV=production pm2 start ./app.js  --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fairy@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alan/.npm/_logs/2018-10-14T02_39_25_039Z-debug.log

**Comment by aemoe** [comment]
`
npm i rimraf -g
`
缺个包

**Comment by xxxsf** [comment]
thx  :)
