### ISSUE TITLE
你确定你这个可以正常运行？

### ISSUE THREAD

**Issue by devmsg** [aemoe/fairy#7]

**Comment by aemoe** [comment]
@devmsg  嗯 是呀~ ~
我本地测试没问题~

客户端 
<img width="1371" alt="qq20170502-195128 2x" src="https://cloud.githubusercontent.com/assets/3195853/25616692/d9c44da4-2f70-11e7-8f6f-2c53377c7d18.png">

服务器端
![a2b5b78a-25af-4f02-9768-67dfd411a429](https://cloud.githubusercontent.com/assets/3195853/25616757/232287fe-2f71-11e7-8632-541658720eee.png)

**Comment by devmsg** [comment]
@aemoe  你webpack 什么版本

**Comment by devmsg** [comment]
@aemoe 
![image](https://cloud.githubusercontent.com/assets/15261658/25646676/510de376-2fed-11e7-8fa3-c12b68861e7e.png)

**Comment by aemoe** [comment]
@devmsg  webpack2

**Comment by aemoe** [comment]
@devmsg 我看了下你的报错记录 很简单 你在client文件夹下执行一次npm i 在在根目录执行下就好了
